version: '2'

services:
  app:
    image: node:8.6
    container_name: discordbot
    volumes:
      - .:/app
    entrypoint:
      - /bin/bash
    ports:
      - 3000:3000
    command: -s
    working_dir: /app
    tty: true
